name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to release from"
        required: true
        type: string

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  publish:
    env:
      ORT_VERSION: ${{ inputs.tag || github.ref_name }}
    permissions:
      attestations: write
      contents: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ env.ORT_VERSION }}
          fetch-depth: 0
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4
        with:
          dependency-graph: generate-and-submit
      - name: Build ORT Distributions
        run: ./gradlew :cli:DistTar :cli:DistZip :cli-helper:DistTar :cli-helper:DistZip -x test # TODO don't skip tests
      - name: Generate Release Notes
        run: ./gradlew -q printChangeLog > RELEASE_NOTES.md
      - name: List files
        run: find ./cli/build/distributions/
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $ORT_VERSION --notes-file RELEASE_NOTES.md \
              ./cli/build/distributions/ort-${{ env.ORT_VERSION }}.{tgz,zip} \
              ./cli-helper/build/distributions/orth-$ORT_VERSION.{tgz,zip}*
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2
        with:
          subject-path: |
            ./cli/build/distributions/ort-${{ env.ORT_VERSION }}.tgz
            ./cli/build/distributions/ort-${{ env.ORT_VERSION }}.zip
            ./cli-helper/build/distributions/orth-${{ env.ORT_VERSION }}.tgz
            ./cli-helper/build/distributions/orth-${{ env.ORT_VERSION }}.zip
